version: "3.7"
services:
  consul:
    image: consul:1.7
    container_name: consul
    networks:
      - mynetwork
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: agent -server -bootstrap-expect 1 -ui -data-dir /tmp -client=0.0.0.0
    # command: consul agent -dev -ui
  config:
    build: ./config-server
    container_name: config
    networks:
      - mynetwork
    ports:
      - "8762:8762"
    volumes:
      - ./conf:/config # 此段把本機的config file放入container內
    environment:
      - CONF_FOLDER=file:///config
  gateway:
    build: ./gateway
    container_name: gateway
    restart: on-failure # 失敗重試
    ports:
      - "8763:8763"
    networks:
      - mynetwork
    depends_on:
      - consul
    environment:
      - CONSUL_SERVER=consul
  redis:
    image: redis:5-alpine
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - mynetwork
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

networks:
  mynetwork:
